name: dev

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on:
      - self-hosted
      - dev

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker version
        run: docker -v
      - name: run docker compose
        run: docker-compose -f "docker-compose.yml" up -d --build
