name: dev

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on:
      - self-hosted
      - dev

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-portal

      # - name:
      #   run: docker -v
      # - name: run docker compose
      #   run: docker-compose -f "docker-compose.yml" up -d --build
