name: dev

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on:
      - self-hosted
      - dev

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker version
        run: docker -v
      - name: docker compose version
        run: docker-compose -v
      - name: docker compose build
        run: docker-compose -f "docker-compose.yml" up -d --build

  # deploy:
  #   needs: build
  #   runs-on:
  #     - self-hosted
  #     - dev
  #   steps: 
  #     - name: docker-compose up
  #       run: docker-compose -f "docker-compose.yml" up -d
